# Generated by Django 5.2.5 on 2025-09-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='character',
            field=models.CharField(default='Bronn', max_length=64),
        ),
    ]
